Final PR - Project update
WildCodeSchool/paris-0921-p2-groupe5 pull request #48
Opened 2021-11-18 13:47 UTC by Ambre-Thevenin

PR with : 
- New Geocoding API and function to reduce API calls 
- Shops Module up and running
- Navigation module up and running
- Sparkle module with 2 arrays for Entertainment 
- CSS fixes and updates 
- Several fix commits

2021-11-18 13:53 UTC, Scarabotte approved these changes

2021-11-18 13:54 UTC, AdeCisy approved these changes
Verified : OK for me

2021-11-18 13:54 UTC, Barbeu78 submitted a review, later dismissed

2021-11-18 19:30 UTC, pelegrand requested changes

2021-11-18 19:30 UTC, pelegrand commented on src/components/Nav.jsx
> +      <div className="container">
Use the same CSS method for all your files plain css or modules

2021-11-19 10:04 UTC, pelegrand approved these changes

2021-11-19 10:39 UTC, tyZulh requested changes

2021-11-19 10:39 UTC, tyZulh commented on src/components/HourlyMeteo.jsx
> +  let forecastHours = forecast.slice(0, 8);
Transform this let in a state and apply the slice inside a useEffect 
```suggestion
const [forcastHours, setForecastHours] = useState([]);

useEffect(() => {
  setForcastHours(forcast.slice(0, 8);
}, [forcast])
```

2021-11-19 10:39 UTC, tyZulh commented on src/components/jokes.jsx
> +  const SingleJoke = [...AstroJokes];
Deprecated

2021-11-19 10:48 UTC, tyZulh approved these changes

2021-11-19 10:48 UTC, merged